### ISSUE TITLE
Key-value pair while sending the data is not required

### ISSUE THREAD

**Issue by sonu3706** [stackroute/ibm-w1-tldm-ui#4]
` sendMessage(message: string) {
        this.stompClient.send('/app/chat', {}, JSON.stringify({
            'messageContent': message, 'sender': this.sender, 'receiver': this.receiver
        }))
        ;`

Instead of sending data in key-value pair better send data as an object which internally holds key-value pair

**Comment by mggmanik** [comment]
fixed
